# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-record', '~> 2.13'
gem 'httparty'

group :development do
  gem 'bauble', path: '..'
  gem 'pry', '~> 0.14.2'
  gem 'pry-byebug', '~> 3.10'
end
