# frozen_string_literal: true

source 'https://rubygems.org'

gem 'httparty', '~> 0.22.0'

group :development do
  if ENV['BAUBLE_DEV_GEM_PATH']
    gem 'bauble_core', path: ENV['BAUBLE_DEV_GEM_PATH']
  else
    gem 'bauble_core', path: '/var/task/bauble_core'
  end
end

gem "pry", "~> 0.14.2"
